#!/bin/bash

echo "......................................................"
echo "..............hello_deb installing...................."
echo "......................................................"

systemctl enable hello
systemctl start hello 


